# Generated by Django 2.2.6 on 2019-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20191101_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_api_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
