# Generated by Django 2.2.6 on 2019-11-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_appointment_patient_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_api_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
