# Generated by Django 2.2.6 on 2019-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0005_auto_20191101_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
