# Generated by Django 2.2.6 on 2019-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0009_remove_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exam_room',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
