# Generated by Django 2.2.6 on 2019-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0010_appointment_exam_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
