# Generated by Django 2.2.6 on 2019-11-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0011_patient_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
