# Generated by Django 2.2.6 on 2019-11-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0012_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
